version: "3.9"

services:
  db:
    image: postgres:14-alpine
    restart: always
    expose:
      - '5432'
    volumes:
      - .dbdata:/var/lib/postgresql
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: super_secure_password_987

  app:
    build: ./
    container_name: app-scrap-container
    volumes:
      - ./src:/opt/app
    ports:
      - "5432:5432"
    depends_on:
      - db
volumes:
  postgresql-data: