version: "3.9"

services:

  app:
    container_name: app-container
    network_mode: host
    build:
      context: ./
    volumes:
        - ./:/app
    depends_on:
      - db


  db:
    image: postgres:11-alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    ports:
      - 5432:5432
    expose:
      - 5432

volumes:
  db:
    driver: local